USE KLEAGUE;

DESCRIBE PLAYER;

-- 선수의 모든 정보를 검색
SELECT *
FROM PLAYER;


-- ‘K06’ 팀 선수의 이름, 팀 아이디, 백넘버, 포지션, 키, 몸무게를 검색
SELECT	PLAYER_NAME, TEAM_ID, BACK_NO, POSITION, HEIGHT, WEIGHT
FROM	PLAYER
WHERE	TEAM_ID = 'K06';


-- ‘K06’ 팀 선수의 이름, 팀 아이디, 백넘버, 포지션, 키, 몸무게, 그리고 비만도를 검색
SELECT	PLAYER_NAME, TEAM_ID, BACK_NO, POSITION, HEIGHT, WEIGHT, ROUND(WEIGHT / ((HEIGHT/100)*(HEIGHT/100)), 2) 비만도
FROM	PLAYER
WHERE	TEAM_ID = 'K06';


-- FROM 절의 생략
SELECT LENGTH('SQL EXPERT') AS ColumnLength;
SELECT LOWER('SQL EXPERT') AS 소문자;


-- SELECT ALL(기본값) DISTINCT
SELECT DISTINCT POSITION
FROM PLAYER; 


-- CONCAT(string1,string2, … , stringN): 컬럼과 컬럼, 혹은 컬럼과 문자열을 연결하여, 새로운 컬럼을 생성.
SELECT CONCAT(PLAYER_NAME, '선수,', HEIGHT, 'cm,', WEIGHT, 'kg') 체격정보
FROM PLAYER; 


-- 비교 연산자(=, >, <, >=, <=, <>)
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND
		POSITION = 'MF' AND
		HEIGHT BETWEEN 170 AND 180;
	
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND
		POSITION <> 'MF' AND
		HEIGHT NOT BETWEEN 170 AND 180;
        

-- IN 연산자에 속성의 조합(n-tuple) 사용
SELECT 	PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM 	PLAYER
WHERE 	(POSITION, NATION) IN (('MF','브라질'), ('FW', '러시아')); 

SELECT 	PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM 	PLAYER
WHERE 	(POSITION, NATION) = ('MF','브라질') OR 
		(POSITION, NATION) = ('FW','러시아');
        
SELECT 	PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM 	PLAYER
WHERE 	POSITION IN ('MF', 'FW') AND NATION IN ('브라질', '러시아');

SELECT 	PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM 	PLAYER
WHERE 	(POSITION = 'MF' OR POSITION = 'FW') AND
		(NATION = '브라질' OR NATION = '러시아');
        
        
-- [NOT] LIKE 연산자
SELECT 	PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM 	PLAYER
WHERE 	POSITION LIKE 'MF'; 		/* exact match */

SELECT 	PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM 	PLAYER
WHERE 	PLAYER_NAME LIKE '장%'; /* partial match */


-- IS [NOT] NULL 연산자
SELECT 	PLAYER_NAME 선수이름, POSITION 포지션, TEAM_ID
FROM 	PLAYER
WHERE 	POSITION IS NULL; /* TRUE 혹은 FALSE 리턴 */


