USE KLEAGUE;

DESCRIBE PLAYER;
DESCRIBE STADIUM;

-- 선수의 모든 정보를 검색
SELECT *
FROM PLAYER;

SELECT	*
FROM	STADIUM;

-- ‘K06’ 팀 선수의 이름, 팀 아이디, 백넘버, 포지션, 키, 몸무게를 검색
SELECT	PLAYER_NAME, TEAM_ID, BACK_NO, POSITION, HEIGHT, WEIGHT
FROM	PLAYER
WHERE	TEAM_ID = 'K06';


-- ‘K06’ 팀 선수의 이름, 팀 아이디, 백넘버, 포지션, 키, 몸무게, 그리고 비만도를 검색
SELECT	PLAYER_NAME, TEAM_ID, BACK_NO, POSITION, HEIGHT, WEIGHT, ROUND(WEIGHT / ((HEIGHT/100)*(HEIGHT/100)), 2) 비만도
FROM	PLAYER
WHERE	TEAM_ID = 'K06';


-- FROM 절의 생략
SELECT LENGTH('SQL EXPERT') AS ColumnLength;
SELECT LOWER('SQL EXPERT') AS 소문자;


-- SELECT ALL(기본값) DISTINCT
SELECT DISTINCT POSITION
FROM PLAYER; 

SELECT	TEAM_ID
FROM	PLAYER;

SELECT	DISTINCT TEAM_ID
FROM	PLAYER;


-- CONCAT(string1,string2, … , stringN): 컬럼과 컬럼, 혹은 컬럼과 문자열을 연결하여, 새로운 컬럼을 생성.
SELECT CONCAT(PLAYER_NAME, '선수,', HEIGHT, 'cm,', WEIGHT, 'kg') 체격정보
FROM PLAYER; 

SELECT	CONCAT(PLAYER_NAME, '님 안녕하세요') AS '선수 인사'
FROM	PLAYER;


-- 비교 연산자(=, >, <, >=, <=, <>)
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND
		POSITION = 'MF' AND
		HEIGHT BETWEEN 170 AND 180;
	
SELECT PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID IN ('K02', 'K07') AND
		POSITION <> 'MF' AND
		HEIGHT NOT BETWEEN 170 AND 180;
        

-- IN 연산자에 속성의 조합(n-tuple) 사용
SELECT 	PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM 	PLAYER
WHERE 	(POSITION, NATION) IN (('MF','브라질'), ('FW', '러시아')); 

SELECT 	PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM 	PLAYER
WHERE 	(POSITION, NATION) = ('MF','브라질') OR 
		(POSITION, NATION) = ('FW','러시아');
        
SELECT 	PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM 	PLAYER
WHERE 	POSITION IN ('MF', 'FW') AND NATION IN ('브라질', '러시아');

SELECT 	PLAYER_NAME, TEAM_ID, POSITION, NATION
FROM 	PLAYER
WHERE 	(POSITION = 'MF' OR POSITION = 'FW') AND
		(NATION = '브라질' OR NATION = '러시아');
        
        
-- [NOT] LIKE 연산자
SELECT 	PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM 	PLAYER
WHERE 	POSITION LIKE 'MF'; 		/* exact match */

SELECT 	PLAYER_NAME 선수이름, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM 	PLAYER
WHERE 	PLAYER_NAME LIKE '장%'; /* partial match */


-- IS [NOT] NULL 연산자
SELECT 	PLAYER_NAME 선수이름, POSITION 포지션, TEAM_ID
FROM 	PLAYER
WHERE 	POSITION IS NULL; /* TRUE 혹은 FALSE 리턴 */


-- PK에 있는 값의 수 = 저장된 투플의 개수
SELECT 	COUNT(PLAYER_ID), COUNT(*)
FROM	PLAYER;


-- COUNT는 NULL값은 세지 않는다
SELECT	COUNT(TEAM_ID) '팀 아이디', COUNT(POSITION) 포지션, COUNT(BACK_NO) 백넘버, COUNT(HEIGHT) 키
FROM	PLAYER;


-- COUNT는 ALL(중복된 값도 카운트, 기본값) 또는 DISTINCT(중복된 값 제거)
SELECT	COUNT(DISTINCT TEAM_ID) '팀 아이디', COUNT(DISTINCT POSITION) 포지션,
		COUNT(DISTINCT BACK_NO) 백넘버, COUNT(DISTINCT HEIGHT) 키
FROM	PLAYER;


-- GROUP BY절로 그룹별로 묶은 후, SELECT절에서 집계 함수 적용
SELECT	POSITION, AVG(HEIGHT) '평균 키'
FROM	PLAYER
WHERE	TEAM_ID = 'K10'
GROUP 	BY	POSITION;	/*POSITION 그룹 수만큼 투플 생성*/

SELECT	POSITION 포지션, COUNT(*) 인원수, COUNT(HEIGHT) 키대상, MAX(HEIGHT) 최대키, MIN(HEIGHT) 최소키, ROUND(AVG(HEIGHT), 2) 평균키
FROM	PLAYER
GROUP 	BY	POSITION;	


-- HAVING절은 GROUP BY로 만든 그룹의 조건식이 TRUE인 그룹만 선택
SELECT	POSITION
FROM	PLAYER
GROUP 	BY POSITION
HAVING	POSITION IN ('DF', 'MF');

SELECT	TEAM_ID 팀아이디, COUNT(*) 인원수
FROM	PLAYER
GROUP	BY	TEAM_ID
HAVING	TEAM_ID IN ('K09', 'K14');


-- 하지만 위처럼 하는 것보다 WHERE절에서 조건을 적용해서 대상 투플 수를 줄이는 것이 더 좋음
SELECT	TEAM_ID 팀아이디, COUNT(*) 인원수
FROM	PLAYER
WHERE	TEAM_ID IN ('K09', 'K14')
GROUP	BY TEAM_ID;


-- 동명이인 구하기
SELECT	PLAYER_NAME 선수명, COUNT(PLAYER_NAME) 선수수
FROM	PLAYER
GROUP	BY	PLAYER_NAME
HAVING	COUNT(PLAYER_NAME) >= 2;


-- 5개 그룹 중에서 평균 키가 180 이상인 그룹만 선택
SELECT	POSITION 포지션, ROUND(AVG(HEIGHT), 2) 평균키
FROM	PLAYER
GROUP	BY	POSITION
HAVING	AVG(HEIGHT) >= 180;


-- WHERE절에는 집계함수를 사용할 수 없다.
-- WHERE절은 하나의 투플만 읽고 처리할 수 있어야 한다.
SELECT 	POSITION 포지션, ROUND(AVG(HEIGHT),2) 평균키
FROM 	PLAYER 
WHERE 	AVG(HEIGHT) >= 180 /* 에러 */
GROUP 	BY POSITION;


-- WITH절을 이용한 임시 테이블 생성
WITH TEMP AS (
		SELECT	POSITION, AVG(HEIGHT) AS AVG_HEIGHT
        FROM	PLAYER
        GROUP	BY	POSITION	
)
SELECT	POSITION, AVG_HEIGHT
FROM	TEMP
WHERE	AVG_HEIGHT >= 180;


-- ORDER BY로 오름차순(기본값), 내림차순 정렬
SELECT	PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
FROM	PLAYER
ORDER	BY 포지션; 


-- HEIGHT가 NULL이 아닌 값에 대해 HEIGHT를 내림차순으로, HEIGHT가 같다면 BACK_NO를 오름차순으로
SELECT	PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM	PLAYER
WHERE	HEIGHT IS NOT NULL
ORDER	BY HEIGHT DESC, BACK_NO;

SELECT	PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM	PLAYER
WHERE	HEIGHT IS NOT NULL
ORDER	BY 4 DESC, 3;


-- ORDER BY 절에는 SELECT에 없는 컬럼이 포함될 수 있음
SELECT	PLAYER_ID, POSITION
FROM	PLAYER
ORDER	BY PLAYER_NAME;


-- GROUP BY절을 같이 사용하면, ORDER BY 절에는 SELECT에 없는 컬럼이 포함될 수 없다.
SELECT	POSITION, COALESCE(AVG(HEIGHT),0), COALESCE(AVG(WEIGHT), 0)
FROM	PLAYER
GROUP	BY POSITION
ORDER	BY PLAYER_NAME;					/* Error !! (GROUP BY) */


-- LIMIT절: SELECT문이 출력하는 행(투플)의 최대 개수를 제한
-- 정렬하여 출력하는 행의 최대 개수를 정의함
-- offset : 결과에 포함할 첫번째 행의 위치 (디폴트값은'0'.)
-- row_count : 출력행의 최대 개수
SELECT	STADIUM_ID, STADIUM_NAME, SEAT_COUNT
FROM	STADIUM
ORDER	BY SEAT_COUNT DESC, STADIUM_NAME;

SELECT	STADIUM_ID, STADIUM_NAME, SEAT_COUNT
FROM	STADIUM
ORDER	BY SEAT_COUNT DESC, STADIUM_NAME
LIMIT	3;			/* 0부터 3개 COUNT해라 */

SELECT	STADIUM_ID, STADIUM_NAME, SEAT_COUNT
FROM	STADIUM
ORDER	BY SEAT_COUNT DESC, STADIUM_NAME
LIMIT	1, 3;		/* 1부터 3개 COUNT해라*/


-- 정렬 순서에 따라, 앞에서 n 개 투플을 검색: ORDER BY 절 + LIMIT 절
-- 계산 순위에 따라, 상위 n 번째까지 검색 (동점자 처리): RANK() 함수
-- ROW_NUMBER() : 일련번호 부여, pagination에 활용
SELECT	ROW_NUMBER() OVER (ORDER BY SEAT_COUNT DESC) AS ROW_NUM,
		SEAT_COUNT, STADIUM_NAME
FROM	STADIUM;

SELECT	RANK() OVER (ORDER BY SEAT_COUNT DESC) AS SEAT_RANK,
		SEAT_COUNT, STADIUM_NAME
FROM	STADIUM;


-- 좌석수 많은 10개 경기장
WITH TEMP AS (
		SELECT	ROW_NUMBER() OVER (ORDER BY SEAT_COUNT DESC) AS ROW_NUM, STADIUM_NAME, SEAT_COUNT, STADIUM_ID
        FROM	STADIUM
)
SELECT	STADIUM_ID, STADIUM_NAME, SEAT_COUNT, ROW_NUM
FROM	TEMP
WHERE	ROW_NUM <= 10;


-- 좌석수 많은 순위로 10위까지의 경기장
WITH TEMP AS (
		SELECT	RANK() OVER (ORDER BY SEAT_COUNT DESC) AS ROW_NUM, STADIUM_NAME, SEAT_COUNT, STADIUM_ID
        FROM	STADIUM
)
SELECT	STADIUM_ID, STADIUM_NAME, SEAT_COUNT, ROW_NUM
FROM	TEMP
WHERE	ROW_NUM <= 10;		/* TEMP에서의 컬럼 별칭은 WHERE에서 사용 가능하다!! */


-- 좌석수 규모 기준으로 경기장 순위를 계산. 단, 같은 순위 내에서는 경기장 명칭의 오름차순으로 정렬
SELECT	STADIUM_ID, STADIUM_NAME, SEAT_COUNT, 
		RANK() OVER (ORDER BY SEAT_COUNT DESC, STADIUM_NAME) AS SEAT_RANK
FROM	STADIUM;
-- 위에처럼 하면 SEAT_COUNT가 같아도 SEAT_RANK값에 차이가 나게 된다.

-- SEAT_COUNT가 같을 때 SEAT_RANK도 같은 값을 가지게 하기 위해서
SELECT	STADIUM_ID, STADIUM_NAME, SEAT_COUNT, 
		RANK() OVER (ORDER BY SEAT_COUNT DESC) AS SEAT_RANK
FROM	STADIUM
ORDER	BY SEAT_COUNT DESC, STADIUM_NAME;